Suggested edits for README
paypal/TLS-update pull request #22
Opened 2016-12-18 03:07 UTC by drfleming0227

@bluk @jeff.brateman@getbraintree.com

Suggested edits for README

2016-12-18 03:37 UTC, bluk requested changes
Mostly minor updates. Thanks!

2016-12-18 03:37 UTC, bluk commented on README.md
> +* [To verify Java and TLS versions](#to-verify-java-and-tls-versions)
I think the link on line 39 isn't correct (think it should have `your` in it).

2016-12-18 03:37 UTC, bluk commented on README.md
> +1. For the PayPal legacy Ruby SDK packaged as `PP_Ruby_NVP_SDK.zip`, download this [PP_Ruby_NVP_SDK.zip](https://github.com/paypal/TLS-update/blob/master/ruby/PP_Ruby_NVP_SDK.zip).
This is really a special callout that should probably be in its own section (e.g. something like `PayPal Legacy Ruby SDK Update`) and not part of the verify section.

2016-12-18 03:37 UTC, bluk commented on README.md
Do you think we should add a link to the [Braintree blog post](https://www.braintreepayments.com/blog/updating-your-production-environment-to-support-tlsv1-2/) as well in a different section?

2016-12-18 03:37 UTC, bluk commented on README.md
> +* [To verify your Ruby and TLS versions](#to-verify-your-ruby-and-tls-versions)
The `your` here should match line 249.

2016-12-18 03:37 UTC, bluk commented on README.md
> +* [To verify your Node and TLS versions](#to-verify-your-node-and-tls-versions)
`your` link should match the title on line 279.

2016-12-18 15:32 UTC, drfleming0227 commented
@bluk Incorporated your comments https://github.com/paypal/TLS-update/pull/22/commits/85202614ef546fb41ba7099be75a2681526fe4eb - thanks!

2016-12-19 16:23 UTC, bluk approved these changes

2016-12-31 21:01 UTC, nadhlad approved these changes

2017-01-02 07:18 UTC, merged